# Generated by Django 5.2.4 on 2025-07-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_cv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='languages',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
